version: 2

builds:
  - main: ./cmd/chatr
    binary: chatr
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/teamcutter/chatr/internal/version.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ 'tar.gz' ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
